analysis: hhbbtt
type: nonresonant
                
model:
  parameters: [ kl, k2v ]
  #parameters: [ kl]
  #parameters: [ ]
  param_dependent_bkg: false
  input_file_pattern: ${ERA}/merged/bbtautau_mass/tmp/all_histograms_bbtautau_mass_Central.root
  #var_to: tautau_m_vis

hist_bins: [ 250, 300, 350, 400, 450, 500, 600, 1000 ]
signalFractionForRelevantBins: 0.20

eras:
  - Run3_2022EE

channels:
  - eTau
  - muTau
  - tauTau

categories:
  - OS_Iso/res2b_cat3
  - OS_Iso/res1b_cat3
  - OS_Iso/boosted_cat3_masswindow

processes:
  # Data / Asimov
  - process: data_obs
    is_data: true
    is_asimov_data: true

  # - process: ggHH_kl_${kl}_kt_1_hbbhtt
  #   hist_name: GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p00
  #   is_signal: true
  #   #  sigma(ggF-HH 13.6 TeV) ~ 34.13 fb   * 2 * BR(bb) * BR(tautau)
  #   scale: 2 * 6.272E-02 * 5.824E-01 * 34.13E-03
  #   param_values: [1, 2.45, 5]

  - process: ggHH_kl_1_kt_1_hbbhtt
    hist_name: GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p00
    is_signal: true
    scale: 2 * 0.5824 * 0.06272 * 0.034170   # 34.170 fb
    param_values: [1.0, 1.0]

  - process: ggHH_kl_2p45_kt_1_hbbhtt
    hist_name: GluGlutoHHto2B2Tau_kl_2p45_kt_1p00_c2_0p00_LHEweights
    is_signal: true
    scale: 2 * 0.5824 * 0.06272 * 0.014814
    param_values: [2.45, 1.0]

  - process: ggHH_kl_5_kt_1_hbbhtt
    hist_name: GluGlutoHHto2B2Tau_kl_5p00_kt_1p00_c2_0p00
    is_signal: true
    scale: 2 * 0.5824 * 0.06272 * 0.097259
    param_values: [5.0, 1.0]
  
  # VBF samples
  - process: qqHH_CV_1p74_C2V_1p37_kl_14p4_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_1p74_C2V_1p37_C3_14p4
    is_signal: true
    scale: 0.4002163 * 2 * 6.272E-02 * 5.824E-01
    param_values: [14.4, 1.37]
  
  - process: qqHH_CV_m0p012_C2V_0p030_kl_10p2_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_m0p012_C2V_0p030_C3_10p2
    is_signal: true
    scale: 0.0000127 * 2 * 6.272E-02 * 5.824E-01
    param_values: [10.2, 0.030]
  
  - process: qqHH_CV_m0p758_C2V_1p44_kl_m19p3_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_m0p758_C2V_1p44_C3_m19p3
    is_signal: true
    scale: 0.3593242 * 2 * 6.272E-02 * 5.824E-01
    param_values: [-19.3, 1.44]
  
  - process: qqHH_CV_m0p962_C2V_0p959_kl_m1p43_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_m0p962_C2V_0p959_C3_m1p43
    is_signal: true
    scale: 0.0011275 * 2 * 6.272E-02 * 5.824E-01
    param_values: [-1.43, 0.959]
  
  - process: qqHH_CV_m1p21_C2V_1p94_kl_m0p94_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_m1p21_C2V_1p94_C3_m0p94
    is_signal: true
    scale: 0.0037987 * 2 * 6.272E-02 * 5.824E-01
    param_values: [-0.94, 1.94]
  
  - process: qqHH_CV_m1p60_C2V_2p72_kl_m1p36_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_m1p60_C2V_2p72_C3_m1p36
    is_signal: true
    scale: 0.0117008 * 2 * 6.272E-02 * 5.824E-01
    param_values: [-1.36, 2.72]
  
  - process: qqHH_CV_m1p83_C2V_3p57_kl_m3p39_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_m1p83_C2V_3p57_C3_m3p39
    is_signal: true
    scale: 0.0168528 * 2 * 6.272E-02 * 5.824E-01
    param_values: [-3.39, 3.57]
  
  - process: qqHH_CV_m2p12_C2V_3p87_kl_m5p96_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_m2p12_C2V_3p87_C3_m5p96
    is_signal: true
    scale: 0.6800842 * 2 * 6.272E-02 * 5.824E-01
    param_values: [-5.96, 3.87]
  
  - process: qqHH_CV_1_C2V_0_kl_1_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_1_C2V_0_C3_1
    is_signal: true
    scale: 0.0296772 * 2 * 6.272E-02 * 5.824E-01
    param_values: [1.0, 0.0]
  
  - process: qqHH_CV_1_C2V_1_kl_1_hbbhtt
    hist_name: VBFHHto2B2Tau_CV_1_C2V_1_C3_1
    is_signal: true
    scale: 0.0019292 * 2 * 6.272E-02 * 5.824E-01
    param_values: [1.0, 1.0]
  
  # Main background
  - process: TT
  - process: DY
    #allow_negative_bins_within_error: True
  - process: VV
  - process: ST

# ------------------------------------------------------------------
uncertainties:
  # Integrated luminosity (Run-3 13.6 TeV)
  - name: lumi_13TeV
    type: lnN
    value: 0.014  # https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3

  - name: MuonID_TightID
    type: shape
    channels: [muTau]
  - name: MuonID_TightIDIso
    type: shape
    channels: [muTau]
  # - name: EleID_TightIDIso
  #   type: shape
  #   channels: [eTau]

  #- name: SingleEleTrg
  - name: HLT_singleEle
    type: shape
    channels: [eTau]
  #- name: SingleMuonTrg
  - name: HLT_singleMu
    type: shape
    channels: [muTau]

  - name: PileUp_Lumi_MC
    type: shape
    eras:
    - Run3_2022EE
# ------------------------------------------------------------------
# Combine helper thresholds & autoMCStats
# ------------------------------------------------------------------
autolnNThr: 0.1
asymlnNThr: 0.001
ignorelnNThr: 0.001

autoMCStats:
  apply: true
  threshold: 20
  apply_to_signal: true
  mode: 1

# cmsEnv python3 StatInference/dc_make/create_datacards.py \
#   --input /eos/user/y/yumeng/HH_bbtautau_Run3/histograms/2022EERun3_20250327Add2GGF \
#   --output StatInference/config/datacards/20250806add2ggf_22EE_fix_3mass \
#   --config StatInference/config/yaml_folder/20250806_22EE_fix_2.yaml
  

